// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9v6xdvp1oc-G-e4sRGWWQCiVk7q8Ijw',
    appId: '1:157653924729:web:1cb9c21ec941b7ad22cda8',
    messagingSenderId: '157653924729',
    projectId: 'ibmdashboarddemo',
    authDomain: 'ibmdashboarddemo.firebaseapp.com',
    storageBucket: 'ibmdashboarddemo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYuw2g3MT-nXsB5niGmCQj0ejnjfv06N8',
    appId: '1:157653924729:android:a0798d06d6f33b1822cda8',
    messagingSenderId: '157653924729',
    projectId: 'ibmdashboarddemo',
    storageBucket: 'ibmdashboarddemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMml8oXGaYx8vEGrCANmLzkNZt-7LoQcA',
    appId: '1:157653924729:ios:d45d54875516547022cda8',
    messagingSenderId: '157653924729',
    projectId: 'ibmdashboarddemo',
    storageBucket: 'ibmdashboarddemo.appspot.com',
    iosClientId: '157653924729-mpi4h3514g7k3bn37ch5ftam2pj2n1sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.prologiumProjectDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMml8oXGaYx8vEGrCANmLzkNZt-7LoQcA',
    appId: '1:157653924729:ios:9c725b0feaea30f722cda8',
    messagingSenderId: '157653924729',
    projectId: 'ibmdashboarddemo',
    storageBucket: 'ibmdashboarddemo.appspot.com',
    iosClientId: '157653924729-bejilfemuq2najp6f43oc8l8hn7q0noe.apps.googleusercontent.com',
    iosBundleId: 'com.example.prologiumProjectDemo.RunnerTests',
  );
}
